version: '3.8'
services:
  app:
    build:
      context: .
      target: app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=eep
      - POSTGRES_PASSWORD=1903
      - POSTGRES_DB=mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "mydatabase"]
      interval: 5s
      timeout: 10s
      retries: 10